# Generated by Django 4.2 on 2024-08-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='ano_lanzamiento',
        ),
        migrations.AddField(
            model_name='album',
            name='año_lanzamiento',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
