# Generated by Django 4.2 on 2024-08-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_album_año_lanzamiento_alter_album_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='año_lanzamiento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
